// SPDX-FileCopyrightText: Copyright The Moby Authors
// SPDX-License-Identifier: Apache-2.0

package apparmor

import "strings"

// NOTE: This profile is replicated in containerd and libpod. If you make a
//       change to this profile, please make follow-up PRs to those projects so
//       that these rules can be synchronised (because any issue with this
//       profile will likely affect libpod and containerd).

// baseTemplate defines the default apparmor profile for containers.
//
// It explicitly sets the AppArmor ABI to 3.0. In AppArmor ABI higher than 4.0,
// "network" no longer includes "network unix", resulting in access to unix sockets
// being denied. We use ABI 3.0 to account for some LTS distros that do not
// yet support ABI 4.0.
//
// See https://gitlab.com/apparmor/apparmor/-/issues/561
// And https://github.com/containerd/containerd/issues/12726
const baseTemplate = `# profile generated by github.com/moby/profiles/apparmor.
{{if .Abi}}abi <{{.Abi}}>,
{{- end}}
{{range $value := .Imports}}
{{$value}}
{{- end}}

profile {{.Name}} flags=(attach_disconnected,mediate_deleted) {
{{- range $value := .InnerImports}}
  {{$value}}
{{- end}}{{if .InnerImports}}
{{end}}
  network,
  # Disallow AF_ALG (Linux kernel crypto API); see https://copy.fail/
  deny network alg,
  # Disallow AF_VSOCK to prevent host/guest communication.
  deny network vsock,
  capability,
  file,
  umount,
  # Host (privileged) processes may send signals to container processes.
  signal (receive) peer=unconfined,
  # runc may send signals to container processes (for "docker stop").
  signal (receive) peer=runc,
  # crun may send signals to container processes (for "docker stop" when used with crun OCI runtime).
  signal (receive) peer=crun,
  # dockerd may send signals to container processes (for "docker kill").
  signal (receive) peer={{.DaemonProfile}},
  # Container processes may send signals amongst themselves.
  signal (send,receive) peer={{.PeerName}},

  deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
  # deny write to files not in /proc/<number>/** or /proc/sys/**
  deny @{PROC}/{[^1-9/],[^1-9/][^0-9/],[^1-9s/][^0-9y/][^0-9s/],[^1-9/][^0-9/][^0-9/][^0-9/]*}/** w,
  deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
  deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} w,  # deny everything except shm* in /proc/sys/kernel/
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/kcore rwklx,

  deny mount,

  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/** rwklx,
  deny /sys/devices/virtual/powercap/** rwklx,
  deny /sys/kernel/security/** rwklx,

  # allow processes within the container to trace each other,
  # provided all other LSM and yama setting allow it.
  ptrace (trace,tracedby,read,readby) peer={{.PeerName}},
}
`

// profileData holds information about the given profile for generation.
type profileData struct {
	// abi is the ABI version to use.
	abi string
	// name is profile name.
	name string
	// daemonProfile is the profile name of our daemon.
	daemonProfile string
	// imports defines the AppArmor functions to import, before defining the profile.
	imports []string
	// innerImports defines the AppArmor functions to import in the profile.
	innerImports []string
}

// Abi returns the AppArmor ABI version used by the profile.
func (d profileData) Abi() string {
	return d.abi
}

// Name returns the quoted AppArmor profile name.
func (d profileData) Name() string {
	return quoteProfileName(d.name)
}

// PeerName returns the quoted AppArmor peer pattern matching the profile name.
func (d profileData) PeerName() string {
	return quotePeerName(d.name)
}

// Imports returns the AppArmor functions imported before the profile definition.
func (d profileData) Imports() []string {
	return d.imports
}

// InnerImports returns the AppArmor functions imported inside the profile.
func (d profileData) InnerImports() []string {
	return d.innerImports
}

// DaemonProfile returns the daemon's quoted peer pattern or the unconfined selector.
func (d profileData) DaemonProfile() string {
	if d.daemonProfile == "unconfined" {
		return d.daemonProfile
	}
	return quotePeerName(d.daemonProfile)
}

// quoteProfileName quotes a profile declaration name. Declaration names retain
// AARE escapes, so only embedded quotes are escaped here. The parser still
// decodes recognized backslash escape sequences.
func quoteProfileName(s string) string {
	if s == "" {
		return ""
	}
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}

// quotePeerName returns s as a quoted AppArmor peer pattern, escaping
// characters as needed to preserve the name literally rather than interpreting
// it as an AARE pattern. Empty strings are returned unchanged.
//
// AppArmor quoted identifiers may contain any character other than NUL. When
// processing an identifier, the parser decodes escape sequences while
// preserving escapes for AARE special characters so they can be handled by
// the pattern-matching backend.
//
// Callers are expected to pass valid profile names, which excludes NUL.
//
// See:
//   - https://gitlab.com/apparmor/apparmor/-/blob/v5.0.2/parser/parser_lex.l#L286-287
//   - https://gitlab.com/apparmor/apparmor/-/blob/v5.0.2/parser/parser_misc.c#L468-507
//   - https://gitlab.com/apparmor/apparmor/-/blob/v5.0.2/parser/lib.c#L144-219
func quotePeerName(s string) string {
	if s == "" {
		return ""
	}

	var b strings.Builder
	b.Grow(len(s) + 2)

	b.WriteByte('"')
	for i := range len(s) {
		c := s[i]
		switch c {
		case '\\', '"', '*', '?', '[', ']', '{', '}', '^', ',':
			b.WriteByte('\\')
		}
		b.WriteByte(c)
	}
	b.WriteByte('"')

	return b.String()
}
